name: mad2_leaderboard
description: Displays the leaderboard for the JagHub app for FBLA's Coding and Programming Event. 2022-23.

repository: https://github.com/MahirEmran/JagHub_Leaderboard.git
version: 1.1.3

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  mad2_db_dataobjects: ^1.0.5
  material_design_icons_flutter: 6.0.7096


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-SemiBold.ttf  
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-ExtraBold.ttf    