name: mad2_leaderboard
description: Displays the leaderboard for MAD2.

repository: https://github.com/MahirEmran/MAD2_Leaderboard.git
version: 1.0.2

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  mad2_db_dataobjects: ^1.0.3
  material_design_icons_flutter: 6.0.7096
  mad2_browsepage: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
